import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conduit",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* header без аутентифакации */}
          <nav>
            <div>
              <a href="./">Conduit</a>
              <ul>
                <li>
                  <a href="/">Home</a>
                </li>
                <li>
                  <a href="/">Sign in</a>
                </li>
                <li>
                  <a href="/">Sign up</a>
                </li>
              </ul>
            </div>
          </nav>
          <div>
            <h1>Conduit</h1>
            <h2>A place to share your knowledge|</h2>
          </div>
        </header>
        {/* <header>
          //header с аутентифакацией 
          <nav>
            <div>
              <a href="./">Conduit</a>
              <ul>
                <li>
                  <a href="/">Home</a>
                </li>
                <li>
                  <a href="/">New Article</a>
                </li>
                <li>
                  <a href="/">Settings</a>
                </li>
                <li>
                  <a href="/">
                    <img src="" alt="profile-photo" />
                  </a>
                </li>
              </ul>
            </div>
          </nav>
          <div>
            <h1>Conduit</h1>
            <h2>A place to share your knowledge|</h2>
          </div>
        </header> */}
        {children}
        <footer>
          <div>
            <a href="/">Conduit</a>
          </div>
          <p>
            An interactive learning project from Thinkster. Code & design
            licensed under MIT.
          </p>
        </footer>
      </body>
    </html>
  );
}
